export let items = [
    {
        id: "wheat",
        name: "Wheat",
        type: "resource",
        category: "farming",
        rarity: "common",
        stackable: true,
    },
    {
        id: "carrot",
        name: "Carrot",
        type: "resource",
        category: "farming",
        rarity: "common",
        stackable: true,
    },
    {
        id: "iron_ore",
        name: "Iron Ore",
        type: "resource",
        category: "mining",
        rarity: "common",
        stackable: true,
    },
    {
        id: "gold_ore",
        name: "Gold Ore",
        type: "resource",
        category: "mining",
        rarity: "common",
        stackable: true,
    },
    {
        id: "oak_log",
        name: "Oak Log",
        type: "resource",
        category: "foraging",
        rarity: "common",
        stackable: true,
    },
    {
        id: "goblin_ear",
        name: "Goblin Ear",
        type: "resource",
        category: "combat",
        rarity: "common",
        stackable: true,
    },

    {
        id: "iron_sword",
        name: "Iron Sword",
        type: "sword",
        category: "weapons",
        rarity: "common",
        stackable: false,
        itemStats: {
            damage: 10,
            strength: 10,
        },
    },
    {
        id: "steel_sword",
        name: "Steel Sword",
        type: "sword",
        category: "weapons",
        rarity: "uncommon",
        stackable: false,
        itemStats: {
            damage: 15,
            strength: 10,
            critical_damage: 5,
        },
    },
    {
        id: "iron_helmet",
        name: "Iron Helmet",
        type: "helmet",
        category: "armor",
        rarity: "common",
        stackable: false,
        itemStats: {
            health: 10,
            defense: 5,
        },
    },
    {
        id: "explorer_boots",
        name: "Explorer Boots",
        type: "boots",
        category: "armor",
        rarity: "uncommon",
        stackable: false,
        itemStats: {
            health: 20,
            defense: 5,
        },
    },
    {
        id: "iron_pickaxe",
        name: "Iron Pickaxe",
        type: "pickaxe",
        category: "tools",
        rarity: "common",
        stackable: false,
        itemStats: {
            mining_fortune: 10,
        },
    },
    {
        id: "steel_axe",
        name: "Steel Axe",
        type: "axe",
        category: "tools",
        rarity: "uncommon",
        stackable: false,
        itemStats: {
            strength: 5,
            foraging_fortune: 10,
        },
    },
];